name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # runs daily

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake files
        uses: Platane/snk@v3
        with:
          github_user_name: ASHIK27445
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg

      - name: Push to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B output
          git add github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg
          git commit -m "Update snake graph"
          git push -f origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



